source 'http://rubygems.org'

gem 'rails', '3.0.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development, :test do
  gem 'sqlite3'
end

group :production do
  gem 'mysql'
end

gem 'ar-column-as', :path => '../../../ar-column-as'

group :test do
  gem 'capybara'
  gem 'mocha', :require => false
end
